plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
filters:
  instance-state-name: running
keyed_groups:
  - key: tags.role
    prefix: ""
    separator: ""
hostnames:
  - private-ip-address
compose:
  ansible_host: "(tags.role == 'bastion') | ternary(public_ip_address, private_ip_address)"
